"""init models

Revision ID: ac8505c88f0b
Revises: 
Create Date: 2025-08-27 23:11:53.355257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac8505c88f0b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('RUNNING', 'COMPLETE', 'FAILED', name='reportstatus'), nullable=False),
    sa.PrimaryKeyConstraint('report_id')
    )
    op.create_table('timezone',
    sa.Column('store_id', sa.UUID(), nullable=False),
    sa.Column('timezone_str', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('store_id')
    )
    op.create_index(op.f('ix_timezone_store_id'), 'timezone', ['store_id'], unique=True)
    op.create_table('menu_hours',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('store_id', sa.UUID(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('start_time_local', sa.Time(), nullable=True),
    sa.Column('end_time_local', sa.Time(), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['timezone.store_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('report_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('RUNNING', 'COMPLETE', 'FAILED', name='reportstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['reports.report_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('report_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=True),
    sa.Column('store_id', sa.UUID(), nullable=True),
    sa.Column('uptime_last_hour_in_minutes', sa.Integer(), nullable=True),
    sa.Column('uptime_last_day_in_hours', sa.Integer(), nullable=True),
    sa.Column('uptime_last_week_in_hours', sa.Integer(), nullable=True),
    sa.Column('downtime_last_hour_in_minutes', sa.Integer(), nullable=True),
    sa.Column('downtime_last_day_in_hours', sa.Integer(), nullable=True),
    sa.Column('downtime_last_week_in_hours', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['reports.report_id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['timezone.store_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('store_status',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('store_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('timestamp_utc', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['timezone.store_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('store_status')
    op.drop_table('report_results')
    op.drop_table('report_jobs')
    op.drop_table('menu_hours')
    op.drop_index(op.f('ix_timezone_store_id'), table_name='timezone')
    op.drop_table('timezone')
    op.drop_table('reports')
    # ### end Alembic commands ###
